services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: gpb-oracle-local
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123   # mật khẩu SYS/SYSTEM — đổi mạnh hơn
    volumes:
      - gpb_oracle_data:/opt/oracle/oradata
    shm_size: "1g"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes:
  gpb_oracle_data: