-- Bảng từ chối bệnh phẩm (module độc lập)
CREATE TABLE BML_SAMPLE_REJECTIONS (
    ID                VARCHAR2(36) PRIMARY KEY,
    PATIENT_NAME      NVARCHAR2(200) NOT NULL,
    DATE_OF_BIRTH     DATE NOT NULL,
    GENDER            NVARCHAR2(20) NOT NULL,
    DIAGNOSIS         NVARCHAR2(500) NOT NULL,
    TEST_INDICATION   NVARCHAR2(500) NOT NULL,
    ORDERING_DOCTOR   NVARCHAR2(200) NOT NULL,
    PATIENT_ADDRESS   NVARCHAR2(500) NOT NULL,
    SAMPLE_CODE       NVARCHAR2(100) NOT NULL,
    SAMPLING_SITE     NVARCHAR2(200) NOT NULL,
    SAMPLING_METHOD   NVARCHAR2(200) NOT NULL,
    REJECTION_TIME    TIMESTAMP NOT NULL,
    REJECTION_REASON  NVARCHAR2(1000) NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(36),
    UPDATED_BY        VARCHAR2(36),
    VERSION           NUMBER DEFAULT 1 NOT NULL
);

CREATE INDEX IDX_BML_SAMP_REJ_PATIENT ON BML_SAMPLE_REJECTIONS (PATIENT_NAME);
CREATE INDEX IDX_BML_SAMP_REJ_CODE ON BML_SAMPLE_REJECTIONS (SAMPLE_CODE);
